spring:
  data:
    mongodb:
      username: financio
      password: rLuadVlqMLa5vYcS
      uri: mongodb+srv://${spring.data.mongodb.username}:${spring.data.mongodb.password}@cluster0.ddayyi8.mongodb.net/?retryWrites=true&w=majority
      database: financio